config/routes.rb
Rails.application.routes.draw do
  
  root 'main#welcome'
  get 'main/welcome'
  
  # Routing used on home page to get to pages in buttons
  get '/ingredient_search' => 'ingredients#search'
  get '/recipe_search' => 'recipes#search'
  get '/recipe_glossary' => 'recipes#glossary'
  
  #Routing for header
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  
  # Routing used for footer
  get 'main/welcome'
  get '/contact' => 'main#contact'
  get '/about' => 'main#about'
  get '/help' => 'main#help'
  
  # Used in AJAX for recipes
  post '/recipe_search', to: 'recipes#search'
  post '/recipe_glossary', to: 'recipes#glossary'
  
  # db elements 
  resources :ingredients
  resources :recipes
  resources :ingredients_recipes
  resources :users
  
  resources :recipe do
    collection do
      match 'search' => 'recipe#search', via: [:get, :post], as: :search
    end
  end
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  
  validates :name,  presence: true, length: { maximum: 50 }
  validates :instructions, presence: true, length: {minimum: 5, maximum: 1000 }
  validate :must_have_at_least_one
  
  has_many :ingredients_recipes
  has_many :ingredients, :through => :ingredients_recipes
  belongs_to :user
  
  private

  def must_have_at_least_one
    errors.add(:base, 'You must select at least one ingredient') unless ingredient_ids.count > 0
  end
      
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  

  # allows user to search for recipes
  def search
    
    # taken from rails lecture slide 9
    name = params[:search] + '%' unless params[:search].nil?
    
    @recipes = Recipe.where(['name LIKE ?', name])
    
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  
  # glossary of all recipes
  def glossary
    
    @recipes, @alphaParams = Recipe.all.alpha_paginate(params[:letter], {:bootstrap3 => true, :paginate_all => false, :pagination_class => "pagination-centered"}){|recipe| recipe.name}
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /recipes
  # GET /recipes.json
  
  
  
   
  def index    
    @recipes = Recipe.all
    @ingredients = Ingredient.all
    
  end
 
  

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    #Trying to get user to work for new recipe
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params.merge(:user => current_user))
    
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :instructions }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :instructions, ingredient_ids: [])
    end
    
    
end

    

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<div class="col-12">
  <%= form_for(recipe) do |f| %>
    <% if recipe.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
  
        <ul>
        <% recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
  
    <div class="field">
      <%= f.label :instructions %>
      <%= f.text_area :instructions %>
    </div>
    
  <div class="field">
    
    <%= f.label :Ingredients %>
    <%= hidden_field_tag "recipe[ingredient_ids][]", nil %>
    <% Ingredient.all.each do |ingredient| %>
      <%= check_box_tag "recipe[ingredient_ids][]", ingredient.id %>
      <%= ingredient.name %><br>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/_instructions.html.erb
<%= form_for(recipe) do |f| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :instructions %>
    <%= f.text_field :instructions %>
  </div>
  
  <div class="field">
    
    <%= f.label :Ingredients %>
    <%= hidden_field_tag "recipe[ingredient_ids][]", nil %>
    <% Ingredient.all.each do |ingredient| %>
      <%= check_box_tag "recipe[ingredient_ids][]", ingredient.id %>
      <%= ingredient.name %><br>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

 

app/views/recipes/_recipe.html.erb
<tr>
  <td><%= recipe.name %></td>
  <td><%= recipe.instructions %></td>
</tr>

app/views/recipes/_results.html.erb
<table width="100%" border="1">

  <thead>
    <tr>
      <th width="25%">Name</th>
      <th width="75%">Instructions</th>
    </tr>
  </thead>
  
  <tbody>
    <%= render @recipes %>
  </tbody>
  
</table>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/glossary.html.erb
<% provide(:title, "Recipe Glossary") %>

<div class="container">
  <div class="row">
    <div class="col-12">
      <h2>Recipe Glossary Page</h2>
      <h4>Check recipe names in our glossary here!</h4>
    </div>
  </div>
  
  <div class = "row">
    <div class="col-xm-12">
      <%= alphabetical_paginate @alphaParams %>
      
      <br>
        
      <div id="pagination_table" class="col-xm-12">
        <br>
        <div id="results" class="col-xm-12">
          <%= render 'results' %>
        </div>
        <br>
      </div>
      
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Instructions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= recipe.instructions %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/instructions.html.erb
<% provide(:title, "Validation Page") %>

<h1>Please enter the required fields</h1>

<%= render "instructions", recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/new.html.erb
<% provide(:title, "New Recipe") %>

<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

app/views/recipes/search.html.erb
<% provide(:title, "Recipe Search") %>

<div class="container">
  
  <div class="row">
    <div class="col-12">
      <h2>Recipe Search Page</h2>
      <h4>Search for a recipe here!</h4>
    </div>
  </div>
      
  <br>
  
  <div class="row">
    <div class="input-group col-lg-6 col-sm-12">
      <%= form_tag(recipe_search_path, remote: true, id:"recipe_search_form") do %>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", name: nil %>
      <% end %>
    </div>
  </div>
  
  <br>
  
  <div class="row">
    <div class="col-12" id="results">
      <%= render 'results' %>
    </div>
  </div>
    
</div>

app/views/recipes/search.js.erb
$("#results").html(
    "<%= escape_javascript (render("results")) %>"); 
    

app/views/recipes/show.html.erb
<% provide(:title, "Recipe View") %>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Ingredients</strong>
    <% @recipe.ingredients.each do |ingredient| %>
     <%= ingredient.name %>
    <% end %>
</p>

<p>
  <strong>Instructions:</strong>
  <%= @recipe.instructions %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Home', root_path %>