config/routes.rb
Rails.application.routes.draw do
  
  root 'main#welcome'
  get 'main/welcome'
  
  # Routing used on home page to get to pages in buttons
  get '/ingredient_search' => 'ingredients#search'
  get '/recipe_search' => 'recipes#search'
  get '/recipe_glossary' => 'recipes#glossary'
  
  #Routing for header
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  
  # Routing used for footer
  get 'main/welcome'
  get '/contact' => 'main#contact'
  get '/about' => 'main#about'
  get '/help' => 'main#help'
  
  # Used in AJAX for recipes
  post '/recipe_search', to: 'recipes#search'
  post '/recipe_glossary', to: 'recipes#glossary'
  
  # db elements 
  resources :ingredients
  resources :recipes
  resources :ingredients_recipes
  resources :users
  
  resources :recipe do
    collection do
      match 'search' => 'recipe#search', via: [:get, :post], as: :search
    end
  end
  
end

app/models/ingredients_recipe.rb
class IngredientsRecipe < ApplicationRecord
  belongs_to :ingredient
  belongs_to :recipe
end

app/controllers/ingredients_recipes_controller.rb
class IngredientsRecipesController < ApplicationController
  before_action :set_ingredients_recipe, only: [:show, :edit, :update, :destroy]

  # GET /ingredients_recipes
  # GET /ingredients_recipes.json
  def index
    @ingredients_recipes = IngredientsRecipe.all
  end

  # GET /ingredients_recipes/1
  # GET /ingredients_recipes/1.json
  def show
  end

  # GET /ingredients_recipes/new
  def new
    @ingredients_recipe = IngredientsRecipe.new
  end

  # GET /ingredients_recipes/1/edit
  def edit
  end

  # POST /ingredients_recipes
  # POST /ingredients_recipes.json
  def create
    @ingredients_recipe = IngredientsRecipe.new(ingredients_recipe_params)

    respond_to do |format|
      if @ingredients_recipe.save
        format.html { redirect_to @ingredients_recipe, notice: 'Ingredients recipe was successfully created.' }
        format.json { render :show, status: :created, location: @ingredients_recipe }
      else
        format.html { render :new }
        format.json { render json: @ingredients_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients_recipes/1
  # PATCH/PUT /ingredients_recipes/1.json
  def update
    respond_to do |format|
      if @ingredients_recipe.update(ingredients_recipe_params)
        format.html { redirect_to @ingredients_recipe, notice: 'Ingredients recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredients_recipe }
      else
        format.html { render :edit }
        format.json { render json: @ingredients_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients_recipes/1
  # DELETE /ingredients_recipes/1.json
  def destroy
    @ingredients_recipe.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_recipes_url, notice: 'Ingredients recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredients_recipe
      @ingredients_recipe = IngredientsRecipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredients_recipe_params
      params.require(:ingredients_recipe).permit(:recipe_id, :ingredient_id)
    end
end

app/helpers/ingredients_recipes_helper.rb
module IngredientsRecipesHelper
end

app/views/ingredients_recipes/_form.html.erb
<%= form_for(ingredients_recipe) do |f| %>
  <% if ingredients_recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredients_recipe.errors.count, "error") %> prohibited this ingredients_recipe from being saved:</h2>

      <ul>
      <% ingredients_recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recipe_id %>
    <%= f.number_field :recipe_id %>
  </div>

  <div class="field">
    <%= f.label :ingredient_id %>
    <%= f.number_field :ingredient_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients_recipes/edit.html.erb
<h1>Editing Ingredients Recipe</h1>

<%= render 'form', ingredients_recipe: @ingredients_recipe %>

<%= link_to 'Show', @ingredients_recipe %> |
<%= link_to 'Back', ingredients_recipes_path %>

app/views/ingredients_recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredients Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Recipe</th>
      <th>Ingredient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients_recipes.each do |ingredients_recipe| %>
      <tr>
        <td><%= ingredients_recipe.recipe_id %></td>
        <td><%= ingredients_recipe.ingredient_id %></td>
        <td><%= link_to 'Show', ingredients_recipe %></td>
        <td><%= link_to 'Edit', edit_ingredients_recipe_path(ingredients_recipe) %></td>
        <td><%= link_to 'Destroy', ingredients_recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredients Recipe', new_ingredients_recipe_path %>

app/views/ingredients_recipes/new.html.erb
<h1>New Ingredients Recipe</h1>

<%= render 'form', ingredients_recipe: @ingredients_recipe %>

<%= link_to 'Back', ingredients_recipes_path %>

app/views/ingredients_recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recipe:</strong>
  <%= @ingredients_recipe.recipe_id %>
</p>

<p>
  <strong>Ingredient:</strong>
  <%= @ingredients_recipe.ingredient_id %>
</p>

<%= link_to 'Edit', edit_ingredients_recipe_path(@ingredients_recipe) %> |
<%= link_to 'Back', ingredients_recipes_path %>