config/routes.rb
Rails.application.routes.draw do
  
  root 'main#welcome'
  get 'main/welcome'
  
  # Routing used on home page to get to pages in buttons
  get '/ingredient_search' => 'ingredients#search'
  get '/recipe_search' => 'recipes#search'
  get '/recipe_glossary' => 'recipes#glossary'
  
  #Routing for header
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  
  # Routing used for footer
  get 'main/welcome'
  get '/contact' => 'main#contact'
  get '/about' => 'main#about'
  get '/help' => 'main#help'
  
  # Used in AJAX for recipes
  post '/recipe_search', to: 'recipes#search'
  post '/recipe_glossary', to: 'recipes#glossary'
  
  # db elements 
  resources :ingredients
  resources :recipes
  resources :ingredients_recipes
  resources :users
  
  resources :recipe do
    collection do
      match 'search' => 'recipe#search', via: [:get, :post], as: :search
    end
  end
  
end

app/views/layouts/_footer.html.erb
<!-- Footer on all page layouts -->
<footer class="footer col-md-12">
  <nav>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        
  <!-- TODO: Add if statement for User information. -->
        
        <% if logged_in? %>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Log out", logout_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to "Sign Up", signup_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<!-- default rails js and ccs loaded -->
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

<%= csrf_meta_tags %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 
                                            'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
        <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
        </script>
    <![endif]-->
    
  </head>
  <body>
    
    <%= render 'layouts/header' %>
    
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
  
    
    <%= yield %>
    
    <%= render 'layouts/footer' %>
  </body>
</html>